// PV ATCK DEF SPEED SPECIAL
export const pokemon = {
	mimikyu: {
		Name: "Mimikyu",
		InternalName: "MIMIKYU",
		Type1: "FAIRY",
		BaseStats: [37, 56, 42, 90, 50, 50],
		GenderRate: "Female50Percent",
		GrowthRate: "Medium",
		BaseEXP: 112,
		EffortPoints: [0, 0, 0, 2, 0, 0],
		Rareness: 190,
		Happiness: 70,
		Abilities: "STATIC",
		HiddenAbility: "LIGHTNINGROD",
		Moves: [1, "TAILWHIP", 1, "THUNDER SHOCK", 5, "GROWL", 7, "PLAYNICE", 10, "QUICKATTACK", 13, "ELECTROBALL", 18, "THUNDER WAVE", 21, "FEINT", 23, "DOUBLETEAM", 26, "SPARK", 29, "NUZZLE", 34, "DISCHARGE", 37, "SLAM", 42, "THUNDER BOLT", 45, "AGILITY", 50, "WILDCHARGE", 53, "LIGHTSCREEN", 58, "THUNDER"],
		TutorMoves: ["ATTRACT", "BRICKBREAK", "CHARGEBEAM", "CONFIDE", "COVET", "DOUBLETEAM", "ECHOEDVOICE", "ELECTROWEB", "FACADE", "FLING", "FOCUSPUNCH", "FRUSTRATION", "GRASSKNOT", "HELPINGHAND", "HIDDENPOWER", "IRONTAIL", "KNOCKOFF", "LASERFOCUS", "LIGHTSCREEN", "MAGNETRISE", "PROTECT", "RAINDANCE", "REST", "RETURN", "ROCKSMASH", "ROUND", "SHOCKWAVE", "SIGNALBEAM", "SLEEPTALK", "SNORE", "STRENGTH", "SUBSTITUTE", "SWAGGER", "THUNDER", "THUNDER BOLT", "THUNDERPUNCH", "THUNDER WAVE", "TOXIC", "VOLTSWITCH", "VOLTTACKLE", "WILDCHARGE"],
		Compatibility: "Field",
		StepsToHatch: 2560,
		Height: 0.4,
		Weight: 6.0,
		Color: "Yellow",
		Shape: "Quadruped",
		Habitat: "Forest",
		Kind: "Mouse",
		Pokedex : "It stores electricity in the electric sacs on its cheeks. When it releases pent-up energy in a burst, the electric power is equal to a lightning bolt.",
		Generation: 1,
		WildItemUncommon: "LIGHTBALL",
		BattlerPlayerX: -5,
		BattlerPlayerY: 0,
		BattlerEnemyX: 4,
		BattlerEnemyY: 14,
		BattlerShadowX: 0,
		BattlerShadowSize: 1,
		Evolutions: ["RAICHU", "Item", "THUNDER STONE"],
		Moves: ["SCRATCH", "TAILWHIP"],
	},
	pidgey : {
		Name : "Pidgey",
		InternalName : "PIDGEY",
		Type1 : "NORMAL",
		Type2 : "FLYING",
		BaseStats : [40,45,40,56,35,35],
		GenderRate : "Female50Percent",
		GrowthRate : "Parabolic",
		BaseEXP : 50,
		EffortPoints : [0,0,0,1,0,0],
		Rareness : 255,
		Happiness : 70,
		Abilities : ["KEENEYE","TANGLEDFEET"],
		HiddenAbility : "BIGPECKS",
		Moves : [1,"TACKLE",5,"SANDATTACK",9,"GUST",13,"QUICKATTACK",17,"WHIRLWIND",21,"TWISTER",25,"FEATHERDANCE",29,"AGILITY",33,"WINGATTACK",37,"ROOST",41,"TAILWIND",45,"MIRRORMOVE",49,"AIRSLASH",53,"HURRICANE"],
		TutorMoves : ["AERIALACE","ATTRACT","CONFIDE","DEFOG","DOUBLETEAM","FACADE","FLY","FRUSTRATION","HEATWAVE","HIDDENPOWER","PROTECT","RAINDANCE","REST","RETURN","ROOST","ROUND","SKYATTACK","SLEEPTALK","SNORE","STEELWING","SUBSTITUTE","SUNNYDAY","SWAGGER","TAILWIND","THIEF","TOXIC","UPROAR","UTURN","WORKUP"],
		EggMoves : ["AIRCUTTER","AIRSLASH","BRAVEBIRD","DEFOG","FEINTATTACK","FORESIGHT","PURSUIT","STEELWING","UPROAR"],
		Compatibility : "Flying",
		StepsToHatch : 3840,
		Height : 0.3,
		Weight : 1.8,
		Color : "Brown",
		Shape : "Winged",
		Habitat : "Forest",
		Kind : "Tiny Bird",
		Pokedex : "It has an extremely sharp sense of direction. It can unerringly return home to its nest, however far it may be removed from its familiar surroundings.",
		Generation : 1,
		BattlerPlayerX : -9,
		BattlerPlayerY : 0,
		BattlerEnemyX : 4,
		BattlerEnemyY : 23,
		BattlerShadowX : 0,
		BattlerShadowSize : 1,
		Evolutions : ["PIDGEOTTO","Level",18],
		Moves: ["TACKLE", "GROWL"],
	},
	rattata : {
		Name : "Rattata",
		InternalName : "RATTATA",
		Type1 : "NORMAL",
		BaseStats : [30,56,35,72,25,35],
		GenderRate : "Female50Percent",
		GrowthRate : "Medium",
		BaseEXP : 51,
		EffortPoints : [0,0,0,1,0,0],
		Rareness : 255,
		Happiness : 70,
		Abilities :[ "RUNAWAY","GUTS,"],
		HiddenAbility : "HUSTLE",
		Moves : [1,"TACKLE",1,"TAILWHIP",4,"QUICKATTACK",7,"FOCUSENERGY",10,"BITE",13,"PURSUIT",16,"HYPERFANG",19,"ASSURANCE",22,"CRUNCH",25,"SUCKERPUNCH",28,"SUPERFANG",31,"DOUBLEEDGE",34,"ENDEAVOR"],
		TutorMoves : ["ATTRACT","BLIZZARD","CHARGEBEAM","CONFIDE","COVET","CUT","DOUBLETEAM","ENDEAVOR","FACADE","FRUSTRATION","GRASSKNOT","HIDDENPOWER","ICEBEAM","ICYWIND","IRONTAIL","LASTRESORT","PROTECT","RAINDANCE","REST","RETURN","ROCKSMASH","ROUND","SHADOWBALL","SHOCKWAVE","SLEEPTALK","SNORE","SUBSTITUTE","SUNNYDAY","SUPERFANG","SWAGGER","TAUNT","THIEF","THUNDER","THUNDERBOLT","THUNDERWAVE","TOXIC","UPROAR","UTURN","WILDCHARGE","WORKUP","ZENHEADBUTT"],
		EggMoves : ["BITE","COUNTER","FINALGAMBIT","FLAMEWHEEL","FURYSWIPES","LASTRESORT","MEFIRST","REVENGE","REVERSAL","SCREECH","UPROAR"],
		Compatibility : "Field",
		StepsToHatch : 3840,
		Height : 0.3,
		Weight : 3.5,
		Color : "Purple",
		Shape : "Quadruped",
		Habitat : "Grassland",
		Kind : "Mouse",
		Pokedex :" A Rattata is cautious in the extreme. Even while it is asleep, it constantly moves its ears and listens for danger. It will make its nest anywhere.",
		Generation : 1,
		WildItemUncommon : "CHILANBERRY",
		BattlerPlayerX : -5,
		BattlerPlayerY : 0,
		BattlerEnemyX : -1,
		BattlerEnemyY : 22,
		BattlerShadowX : 0,
		BattlerShadowSize : 2,
		Evolutions : ["RATICATE","Level",20],
		Moves: ["TACKLE", "TAILWHIP"],
	},
	caterpie: {
		Name : "Caterpie",
		InternalName : "CATERPIE",
		Type1 : "BUG",
		BaseStats : [45,30,35,45,20,20],
		GenderRatio : "Female50Percent",
		GrowthRate : "Medium",
		BaseEXP : 39,
		CatchRate : 255,
		Happiness : 50,
		Abilities : "SHIELDDUST",
		HiddenAbilities : "RUNAWAY",
		Moves : [1,"TACKLE",1,"STRINGSHOT",9,"BUGBITE"],
		TutorMoves : "ELECTROWEB",
		EggGroups : "Bug",
		HatchSteps : 3840,
		Height : 0.3,
		Weight : 2.9,
		Color : "Green",
		Shape : "Insectoid",
		Habitat : "Forest",
		Category : "Worm",
		Pokedex : "Its voracious appetite compels it to devour leaves bigger than itself without hesitation. It releases a terribly strong odor from its antennae.",
		Generation : 1,
		Evolutions : ["METAPOD","Level",7],
		Moves: ["STRINGSHOT",], //  "TACKLE"
	},
	weedle: {
		Name : "Weedle",
		InternalName : "WEEDLE",
		Type1 : "BUG", 
		Type2: "POISON",
		BaseStats : [40,35,30,50,20,20],
		GenderRatio : "Female50Percent",
		GrowthRate : "Medium",
		BaseEXP : 39,
		EVs : ["SPEED",1],
		CatchRate : 255,
		Happiness : 50,
		Abilities : "SHIELDDUST",
		HiddenAbilities : "RUNAWAY",
		Moves : [1,"POISONSTING",1,"STRINGSHOT",9,"BUGBITE"],
		TutorMoves : ["BUGBITE","ELECTROWEB"],
		EggGroups : "Bug",
		HatchSteps : 3840,
		Height : 0.3,
		Weight : 3.2,
		Color : "Brown",
		Shape : "Insectoid",
		Habitat : "Forest",
		Category : ["Hairy", "Bug"],
		Pokedex : "A Weedle has an extremely acute sense of smell. It distinguishes its favorite kinds of leaves from those it dislikes by sniffing with its big red proboscis (nose).",
		Generation : 1,
		Evolutions : ["KAKUNA","Level",7],
		Moves: ["TACKLE", "STRINGSHOT"],
	},
	spearow: {
		Name : "Spearow",
		InternalName : "SPEAROW",
		Type1 : "NORMAL",
		Type2: "FLYING",
		BaseStats : [40,60,30,70,31,31],
		GenderRatio : "Female50Percent",
		GrowthRate : "Medium",
		BaseEXP : 52,
		EVs : ["SPEED",1],
		CatchRate : 255,
		Happiness : 50,
		Abilities : "KEENEYE",
		HiddenAbilities : "SNIPER",
		Moves : [1,"PECK",1,"GROWL",4,"LEER",8,"ASSURANCE",11,"FURYATTACK",15,"AERIALACE",18,"WINGATTACK",22,"TAKEDOWN",25,"AGILITY",29,"FOCUSENERGY",32,"ROOST",36,"DRILLPECK"],
		EggGroups : "Flying",
		HatchSteps : 3840,
		Height : 0.3,
		Weight : 2.0,
		Color : "Brown",
		Shape : "Winged",
		Habitat : "RoughTerrain",
		Category : ["Tiny", "Bird"],
		Pokedex : "Its loud cry can be heard over half a mile away. If its high, keening cry is heard echoing all around, it is a sign that they are warning each other of danger.",
		Generation : 1,
		WildItemUncommon : "SHARPBEAK",
		Evolutions : ["FEAROW","Level",20],
		Moves: ["PECK", "GROWL"],
},






    pikachu: {
		Name: "Pikachu",
		InternalName: "PIKACHU",
		Type1: "ELECTRIC",
		BaseStats: [35, 55, 40, 90, 50, 50],
		GenderRate: "Female50Percent",
		GrowthRate: "Medium",
		BaseEXP: 112,
		EffortPoints: [0, 0, 0, 2, 0, 0],
		Rareness: 190,
		Happiness: 70,
		Abilities: "STATIC",
		HiddenAbility: "LIGHTNINGROD",
		Moves: [1, "TAILWHIP", 1, "THUNDER SHOCK", 5, "GROWL", 7, "PLAYNICE", 10, "QUICKATTACK", 13, "ELECTROBALL", 18, "THUNDER WAVE", 21, "FEINT", 23, "DOUBLETEAM", 26, "SPARK", 29, "NUZZLE", 34, "DISCHARGE", 37, "SLAM", 42, "THUNDER BOLT", 45, "AGILITY", 50, "WILDCHARGE", 53, "LIGHTSCREEN", 58, "THUNDER"],
		TutorMoves: ["ATTRACT", "BRICKBREAK", "CHARGEBEAM", "CONFIDE", "COVET", "DOUBLETEAM", "ECHOEDVOICE", "ELECTROWEB", "FACADE", "FLING", "FOCUSPUNCH", "FRUSTRATION", "GRASSKNOT", "HELPINGHAND", "HIDDENPOWER", "IRONTAIL", "KNOCKOFF", "LASERFOCUS", "LIGHTSCREEN", "MAGNETRISE", "PROTECT", "RAINDANCE", "REST", "RETURN", "ROCKSMASH", "ROUND", "SHOCKWAVE", "SIGNALBEAM", "SLEEPTALK", "SNORE", "STRENGTH", "SUBSTITUTE", "SWAGGER", "THUNDER", "THUNDER BOLT", "THUNDERPUNCH", "THUNDER WAVE", "TOXIC", "VOLTSWITCH", "VOLTTACKLE", "WILDCHARGE"],
		Compatibility: "Field",
		StepsToHatch: 2560,
		Height: 0.4,
		Weight: 6.0,
		Color: "Yellow",
		Shape: "Quadruped",
		Habitat: "Forest",
		Kind: "Mouse",
		Pokedex : "It stores electricity in the electric sacs on its cheeks. When it releases pent-up energy in a burst, the electric power is equal to a lightning bolt.",
		Generation: 1,
		WildItemUncommon: "LIGHTBALL",
		BattlerPlayerX: -5,
		BattlerPlayerY: 0,
		BattlerEnemyX: 4,
		BattlerEnemyY: 14,
		BattlerShadowX: 0,
		BattlerShadowSize: 1,
		Evolutions: ["RAICHU", "Item", "THUNDER STONE"],
		Moves: ["THUNDERSHOCK", "SCRATCH"],
	},
    charmander: {
		Name: "Charmander",
		InternalName: "CHARMANDER",
		Type1: "FIRE",
		BaseStats: [39, 52, 43, 65, 60, 50],
		GenderRate: "FemaleOneEighth",
		GrowthRate: "Parabolic",
		BaseEXP: 62,
		EffortPoints: [0, 0, 0, 1, 0, 0],
		Rareness: 45,
		Happiness: 70,
		Abilities: "BLAZE",
		HiddenAbility: "SOLARPOWER",
		Moves: [1, "SCRATCH", 1, "GROWL", 7, "EMBER", 10, "SMOKESCREEN", 16, "DRAGONRAGE", 19, "SCARYFACE", 25, "FIREFANG", 28, "FLAMEBURST", 34, "SLASH", 37, "FLAMETHROWER", 43, "FIRESPIN", 46, "INFERNO"],
		TutorMoves: ["AERIALACE", "ATTRACT", "BRICKBREAK", "CONFIDE", "CUT", "DOUBLETEAM", "DRAGONCLAW", "DRAGONPULSE", "ECHOEDVOICE", "FACADE", "FIREBLAST", "FIREPLEDGE", "FIREPUNCH", "FLAMECHARGE", "FLAMETHROWER", "FLING", "FOCUSPUNCH", "FRUSTRATION", "HEATWAVE", "HIDDENPOWER", "IRONTAIL", "OVERHEAT", "POWERUPPUNCH", "PROTECT", "REST", "RETURN", "ROCKSLIDE", "ROCKSMASH", "ROCKTOMB", "ROUND", "SHADOWCLAW", "SLEEPTALK", "SNORE", "STRENGTH", "SUBSTITUTE", "SUNNYDAY", "SWAGGER", "SWORDSDANCE", "THUNDER PUNCH", "TOXIC", "WILLOWISP", "WORKUP"],
		EggMoves: ["AIRCUTTER", "ANCIENTPOWER", "BEATUP", "BELLYDRUM", "BITE", "COUNTER", "CRUNCH", "DRAGONDANCE", "DRAGONPULSE", "DRAGONRUSH", "FLAREBLITZ", "FOCUSPUNCH", "METALCLAW", "OUTRAGE"],
		Compatibility: ["Monster", "Dragon"],
		StepsToHatch: 5120,
		Height: 0.6,
		Weight: 8.5,
		Color: "Red",
		Shape: "BipedalTail",
		Habitat: "Mountain",
		Kind: "Lizard",
		Pokedex : "The flame that burns at the tip of its tail is an indication of its emotions. The flame wavers when Charmander is happy, and blazes when it is enraged.",
		Generation: 1,
		BattlerPlayerX: -6,
		BattlerPlayerY: 0,
		BattlerEnemyX: 4,
		BattlerEnemyY: 19,
		BattlerShadowX: 0,
		BattlerShadowSize: 1,
		Evolutions: ["CHARMELEON", "Level", 16],
		Moves: ["SCRATCH"],
	},
	bulbasaur: {
		Name: "Bulbasaur",
		InternalName: "BULBASAUR",
		Type1: "GRASS",
		Type2: "POISON",
		BaseStats: [45, 49, 49, 45, 65, 65],
		GenderRate: "FemaleOneEighth",
		GrowthRate: "Parabolic",
		BaseEXP: 64,
		EffortPoints: [0, 0, 0, 0, 1, 0],
		Rareness: 45,
		Happiness: 70,
		Abilities: "OVERGROW",
		HiddenAbility: "CHLOROPHYLL",
		Moves: [1, "TACKLE", 3, "GROWL", 7, "LEECHSEED", 9, "VINEWHIP", 13, "POISONPOWDER", 13, "SLEEPPOWDER", 15, "TAKEDOWN", 19, "RAZORLEAF", 21, "SWEETSCENT", 25, "GROWTH", 27, "DOUBLEEDGE", 31, "WORRYSEED", 33, "SYNTHESIS", 37, "SEEDBOMB"],
		TutorMoves: ["ATTRACT", "BIND", "CONFIDE", "CUT", "DOUBLETEAM", "ECHOEDVOICE", "ENERGYBALL", "FACADE", "FRUSTRATION", "GIGADRAIN", "GRASSKNOT", "GRASSPLEDGE", "HIDDENPOWER", "KNOCKOFF", "LIGHTSCREEN", "NATUREPOWER", "PROTECT", "REST", "RETURN", "ROCKSMASH", "ROUND", "SAFEGUARD", "SEEDBOMB", "SLEEPTALK", "SLUDGEBOMB", "SNORE", "SOLARBEAM", "STRENGTH", "SUBSTITUTE", "SUNNYDAY", "SWAGGER", "SWORDSDANCE", "SYNTHESIS", "TOXIC", "VENOSHOCK", "WORKUP", "WORRYSEED"],
		EggMoves: ["AMNESIA", "CHARM", "CURSE", "ENDURE", "GIGADRAIN", "GRASSWHISTLE", "GRASSYTERRAIN", "INGRAIN", "LEAFSTORM", "MAGICALLEAF", "NATUREPOWER", "PETALDANCE", "POWERWHIP", "SKULLBASH", "SLUDGE"],
		Compatibility: ["Monster", "Grass"],
		StepsToHatch: 5120,
		Height: 0.7,
		Weight: 6.9,
		Color: "Green",
		Shape: "Quadruped",
		Habitat: "Grassland",
		Kind: "Seed",
		Pokedex : "Bulbasaur can be seen napping in bright sunlight.",
		Generation: 1,
		BattlerPlayerX: -4,
		BattlerPlayerY: 0,
		BattlerEnemyX: -1,
		BattlerEnemyY: 26,
		BattlerShadowX: 0,
		BattlerShadowSize: 2,
		Evolutions: ["IVYSAUR", "Level", 16],
		Moves: ["SCRATCH"],
	},
    eevee: {
		Name: "Eevee",
		InternalName: "EEVEE",
		Type1: "NORMAL",
		BaseStats: [55, 55, 50, 55, 45, 65],
		GenderRate: "FemaleOneEighth",
		GrowthRate: "Medium",
		BaseEXP: 65,
		EffortPoints: [0, 0, 0, 0, 0, 1],
		Rareness: 45,
		Happiness: 70,
		Abilities: ["RUNAWAY", "ADAPTABILITY"],
		HiddenAbility: "ANTICIPATION",
		Moves: [1, "COVET", 1, "HELPINGHAND", 1, "GROWL", 1, "TACKLE", 1, "TAILWHIP", 5, "SANDATTACK", 9, "BABYDOLLEYES", 13, "QUICKATTACK", 17, "BITE", 17, "SWIFT", 20, "REFRESH", 25, "TAKEDOWN", 29, "CHARM", 33, "BATONPASS", 37, "DOUBLEEDGE", 41, "LASTRESORT", 45, "TRUMPCARD"],
		TutorMoves: ["ATTRACT", "CONFIDE", "COVET", "DOUBLETEAM", "ECHOEDVOICE", "FACADE", "FRUSTRATION", "HEALBELL", "HELPINGHAND", "HIDDENPOWER", "HYPERVOICE", "IRONTAIL", "LASERFOCUS", "LASTRESORT", "PROTECT", "RAINDANCE", "REST", "RETURN", "ROUND", "SHADOWBALL", "SLEEPTALK", "SNORE", "SUBSTITUTE", "SUNNYDAY", "SWAGGER", "TOXIC", "WORKUP"],
		EggMoves: ["CAPTIVATE", "CHARM", "COVET", "CURSE", "DETECT", "ENDURE", "FAKETEARS", "FLAIL", "NATURALGIFT", "STOREDPOWER", "SYNCHRONOISE", "TICKLE", "WISH", "YAWN"],
		Compatibility: "Field",
		StepsToHatch: 8960,
		Height: 0.3,
		Weight: 6.5,
		Color: "Brown",
		Shape: "Quadruped",
		Habitat: "Urban",
		Kind: "Evolution",
		Pokedex : "An Eevee has an unstable genetic makeup that suddenly mutates due to its environment. Radiation from various stones causes this Pokémon to evolve.",
		Generation: 1,
		BattlerPlayerX: -7,
		BattlerPlayerY: 0,
		BattlerEnemyX: 0,
		BattlerEnemyY: 20,
		BattlerShadowX: 0,
		BattlerShadowSize: 2,
		Evolutions: ["VAPOREON", "Item", "WATERSTONE", "JOLTEON", "Item", "THUNDER STONE", "FLAREON", "Item", "FIRESTONE", "LEAFEON", "Location", "28", "GLACEON", "Location", "34", "SYLVEON", "HappinessMoveType", "FAIRY", "ESPEON", "HappinessDay","UMBREON", "HappinessNight"],
		Moves: ["SCRATCH"],
	},
}